---
name: haproxy

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: haproxy
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: 
  - name: default
    default: [dns,gateway]
  - name: vip
    static_ips: [((haproxy_vip))]
  jobs:
  - name: haproxy
    release: haproxy
    properties:
      ha_proxy:
        disable_http: ((haproxy_disable_http))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name: bpm
  version: latest
- name: haproxy
  version: 9.5.0
  url: https://github.com/cloudfoundry-incubator/haproxy-boshrelease/releases/download/v9.5.0/haproxy-9.5.0.tgz
  sha1: 651abdeb879f1b5cd3f59a231cb9102b41ffaafd
