- type: replace
  path: /instance_groups/0/jobs/name=haproxy/properties/ha_proxy/tcp?
  value:
    - name: worker
      port: ((haproxy_frontend_port))
      backend_servers: ((haproxy_backend_servers))
      balance: roundrobin
      backend_port: ((haproxy_backend_port))

