- type: replace
  path: /instance_groups/0/jobs/name=haproxy/properties/ha_proxy/tcp?
  value:
    - name: worker
      port: 4443
      backend_servers:
      - 192.168.0.22
      - 192.168.0.23
      - 192.168.0.24
      balance: roundrobin
      backend_port: 31719
      ssl: true
      backend_ssl: noverify

- type: replace
  /instance_groups/0/jobs/name=haproxy/properties/ha_proxy/disable
